#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/281677160/build-actions
# Description: Build OpenWrt using GitHub Actions
#

name: 编译
on:
  workflow_dispatch:

jobs:
  build:
    name: 编译OpenWrt固件
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: 上传固件在 github Artifacts
      uses: actions/upload-artifact@main
      with:
        name: firmware
        path: ${{ env.FIRMWARE_PATH }}
    
    - name: 发布固件
      uses: ncipollo/release-action@v1
      with:
        name: Artifacts
        tag: a555555
        token: ${{ secrets.REPO_TOKEN }}
        allowUpdates: true
        body: 22222222222222222
        artifacts: "${{ env.FIRMWARE_PATH }}/*"
