name: "Make OpenWrt"
author: "https://github.com/ophub/amlogic-s9xxx-openwrt"
description: "Support Amlogic, Rockchip and Allwinner boxes."
inputs:
  mode:
    description: "Select script."
    required: false
    default: "ophub"
  openwrt_path:
    description: "Select armvirt64 file path."
    required: false
    default: "openwrt/bin/targets/*/*/*rootfs.tar.gz"
  openwrt_board:
    description: "Select device board."
    required: false
    default: "all"
  kernel_repo:
    description: "Select kernel repository."
    required: false
    default: "ophub/kernel"
  kernel_usage:
    description: "Set the tags of the stable kernel."
    required: false
    default: "stable"
  openwrt_kernel:
    description: "Select kernel version."
    required: false
    default: "6.1.y_6.12.y"
  auto_kernel:
    description: "Auto use the latest kernel."
    required: false
    default: "true"
  openwrt_size:
    description: "Set the rootfs size(Unit: MiB)."
    required: false
    default: ""
  builder_name:
    description: "Set OpenWrt builder signature."
    required: false
    default: ""
runs:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:    
        - uses: actions/checkout@v4
        - uses: actions/upload-artifact@main
          with:
            name: firmware
            path: ${{ env.FIRMWARE_PATH }}

        - uses: ncipollo/release-action@v1
          with:
            name: Artifacts
            tag: a555555
            token: ${{ secrets.REPO_TOKEN }}
            allowUpdates: true
            body: 22222222222222222
            artifacts: "${{ env.FIRMWARE_PATH }}/*"
branding:
  icon: "terminal"
  color: "gray-dark"
