#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/281677160/build-actions
# Description: Build OpenWrt using GitHub Actions
#

name: 编译OpenWrt固件
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: '请输入您要编译的源码仓库'
        required: true
        default: ''
      REPO_BRANCH:
        description: '请输入源码的分支'
        required: true
        default: ''
      CONFIG_FILE:
        description: '请输入[seed]文件夹里的配置文件名称'
        required: true
        default: ''
      TEMPOARY_IP:
        description: '请输入固件后台IP,默认[192.168.1.1]'
        required: true
        default: ''
      UPLOAD_FIRMWARE:
        description: '上传固件到 Artifacts'
        required: false
        default: 'true'
        type: boolean
      UPLOAD_RELEASE:
        description: '发布固件到 Releases'
        required: false
        default: 'false'
        type: boolean
      CACHEWRTBUILD_SWITCH:
        description: '缓存加速编译'
        required: false
        default: 'true'
        type: boolean
      CHINESE_LANGUAGE_LUCI:
        description: '更改成默认中文LUCI'
        required: false
        default: 'false'
        type: boolean
      DELETE_LOGIN_PASSWORD:
        description: '免密登录固件设置'
        required: false
        default: 'true'
        type: boolean
      PACKAGING_FIRMWARE:
        description: 'Armvirt_64自动打包成img固件'
        required: false
        default: 'true'
        type: boolean


# 定时触发开启开始编译(把下面两个#去掉开启)
  schedule:
   - cron: 25 14 * * *

env:
  # 定时编译的话，设置这里的控制为准
  REPO_URL: coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: x86_64
  TEMPOARY_IP: 192.168.1.1
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  CACHEWRTBUILD_SWITCH: true
  CHINESE_LANGUAGE_LUCI: false
  DELETE_LOGIN_PASSWORD: true
  PACKAGING_FIRMWARE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: 编译固件
    
    env:
      FOLDER_NAME: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [devices]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 检测文件
      run: |
        cd ${GITHUB_WORKSPACE}
        echo "GIT_REPOSITORY=${{github.repository}}" >> $GITHUB_ENV
        echo "REPO_TOKEN=${{ secrets.REPO_TOKEN }}" >> $GITHUB_ENV
        if [[ -n "${{ inputs.REPO_URL }}" ]]; then
          export REPO_URL="https://github.com/$(echo "${{ inputs.REPO_URL }}" |sed s/[[:space:]]//g)"
          export REPO_BRANCH="${{ inputs.REPO_BRANCH }}"
          export CONFIG_FILE="seed/${{ inputs.CONFIG_FILE }}"
          export TEMPOARY_IP="${{ inputs.TEMPOARY_IP }}"
          export UPLOAD_FIRMWARE="${{ inputs.UPLOAD_FIRMWARE }}"
          export UPLOAD_RELEASE="${{ inputs.UPLOAD_RELEASE }}"
          export CACHEWRTBUILD_SWITCH="${{ inputs.CACHEWRTBUILD_SWITCH }}"
          export CHINESE_LANGUAGE_LUCI="${{ inputs.CHINESE_LANGUAGE_LUCI }}"
          export DELETE_LOGIN_PASSWORD="${{ inputs.DELETE_LOGIN_PASSWORD }}"
          export PACKAGING_FIRMWARE="${{ inputs.PACKAGING_FIRMWARE }}"
          export SOURCE="$(echo "${{ inputs.REPO_URL }}" |cut -d"/" -f1 |sed "s/\.//g" |sed "s/\-//g")"
          export LUCI_VERSION="$(echo "${{ inputs.REPO_BRANCH }}" |cut -d"-" -f2-)"
          export DIY_WORK="${SOURCE}$(echo "${LUCI_VERSION}" |sed "s/\.//g" |sed "s/\-//g")"
        else
          export REPO_URL="https://github.com/$(echo "${{ env.REPO_URL }}" |sed s/[[:space:]]//g)"
          export REPO_BRANCH="${{ env.REPO_BRANCH }}"
          export CONFIG_FILE="seed/${{ env.CONFIG_FILE }}"
          export TEMPOARY_IP="${{ env.TEMPOARY_IP }}"
          export UPLOAD_FIRMWARE="${{ env.UPLOAD_FIRMWARE }}"
          export UPLOAD_RELEASE="${{ env.UPLOAD_RELEASE }}"
          export CACHEWRTBUILD_SWITCH="${{ env.CACHEWRTBUILD_SWITCH }}"
          export CHINESE_LANGUAGE_LUCI="${{ env.CHINESE_LANGUAGE_LUCI }}"
          export DELETE_LOGIN_PASSWORD="${{ env.DELETE_LOGIN_PASSWORD }}"
          export PACKAGING_FIRMWARE="${{ env.PACKAGING_FIRMWARE }}"
          export SOURCE="$(echo "${{ env.REPO_URL }}" |cut -d"/" -f1 |sed "s/\.//g" |sed "s/\-//g")"
          export LUCI_VERSION="$(echo "${{ env.REPO_BRANCH }}" |cut -d"-" -f2-)"
          export DIY_WORK="${SOURCE}$(echo "${LUCI_VERSION}" |sed "s/\.//g" |sed "s/\-//g")"
        fi
        if [[ ! -d "${GITHUB_WORKSPACE}/build/${FOLDER_NAME}" ]]; then
          echo -e "\033[31m [build]文件夹里,[${FOLDER_NAME}]名称文件不存在 \033[0m"
          exit 1
        elif [[ ! -f "${GITHUB_WORKSPACE}/common/common.sh" ]]; then
          echo -e "\033[31m [common]文件夹里,[common.sh]文件不存在,请勿删除或随意修改此文件 \033[0m"
          exit 1
        else
          sudo chmod -R +x $GITHUB_WORKSPACE/common
          source ${GITHUB_WORKSPACE}/common/common.sh && wnejian_jiance
        fi

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        source ${GITHUB_WORKSPACE}/common/common.sh && Diy_update
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /${{ env.DIY_WORK }}
        sudo chown $USER:$GROUPS /${{ env.DIY_WORK }}

    - name: 拉取源码
      working-directory: /${{ env.DIY_WORK }}
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /${{ env.DIY_WORK }}/openwrt $GITHUB_WORKSPACE/openwrt
        source $GITHUB_WORKSPACE/common/common.sh && Package_settings

    - name: 读取扩展文件
      run: |
        cd openwrt
        source ${BUILD_PATH}/common.sh && Diy_partsh

    - name: 安装源码插件源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a > /dev/null 2>&1
        ./scripts/feeds install -a
        source ${BUILD_PATH}/common.sh && Diy_config
        
    - name: 编译信息
      continue-on-error: true
      run: |
        cd ${GITHUB_WORKSPACE}
        source ${BUILD_PATH}/common.sh && Diy_xinxi
        
    - name: 缓存加速
      if: env.CACHEWRTBUILD_SWITCH == 'true'
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: "${{ env.TARGET_PROFILE }}"
        prefix: ${{ github.workspace }}/openwrt

    - name: 下载软件源
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 开始编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        cd "${FIRMWARE_PATH}"
        mkdir -p ipk
        cp -rf $(find ${HOME_PATH}/bin/packages/ -type f -name "*.ipk") ipk/ && sync
        sudo tar -czf ipk.tar.gz ipk && sync
        source ${BUILD_PATH}/common.sh && Diy_armvirt
        sudo rm -rf ipk profiles.json packages

    - name: 上传固件至Artifacts
      if: steps.compile.outcome == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE }}-${{ env.LUCI_VERSION }}-${{ env.TARGET_PROFILE }}-${{ env.FILE_DATE }}-firmware
        path: ${{ env.FIRMWARE_PATH }}

    - name: 发布固件到release
      id: release
      if: steps.compile.outcome == 'success' && env.UPLOAD_RELEASE == 'true' && env.REPO_TOKEN
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.FILE_NAME }}
        tag: ${{ env.FILE_TAG }}
        token: ${{ secrets.REPO_TOKEN }}
        body: ${{ env.FILE_DATE }}
        allowUpdates: true
        replacesArtifacts: true
        artifacts: "${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE }}"
        
    - name: 触发Armvirt_64自动打包成img固件
      if: steps.release.outcome == 'success' && env.REPO_TOKEN && env.PACKAGING_FIRMWARE == 'true'
      run: |
        source ${BUILD_PATH}/common.sh && Packaged_services
