name: Immortalwrt-天灵
on:
  workflow_dispatch:

jobs:
  build:
    name: 启动
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
  
    steps:
    - name: 清理Actions空间
      continue-on-error: true
      uses: small-5/delete-workflow-runs@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ github.repository }}
        retain_min: 10
