#
# 打包Amlogic/Rockchip固件,请勿修改文件名称（packaging.yml）
#

name: 打包Amlogic/Rockchip固件
on:
  repository_dispatch:
  workflow_dispatch:


env:
  openwrt_board: s905d
  openwrt_kernel: 6.1.y
  auto_kernel: false
  kernel_usage: stable
  kernel_repo: ophub/kernel
  openwrt_storage: save
  builder_name: angely
  SSH_ACTION: true

jobs:
  build:
    name: 编译
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:    
    - name: 准备结束
      uses: actions/checkout@v4
      
    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential rename pigz clang bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: 拉取源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone -b master --single-branch https://github.com/coolsnowwolf/lede openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    
    - name: 打包固件
      run: |
        cd openwrt
        mkdir -p bin/targets
        wget -q https://github.com/281677160/autobuild/releases/download/targz/Lede-armvirt-64-default-rootfs.tar.gz -O bin/targets/openwrt-armvirt-64-default-rootfs.tar.gz
        echo "HOME_PATH=$GITHUB_WORKSPACE/openwrt/bin/targets" >> ${GITHUB_ENV}

    - name: SSH远程连接（make menuconfig）
      if: env.SSH_ACTION == 'true'
      uses: danshui-git/debugger-action@main

    - name: Packaging OpenWrt
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: ${{ env.HOME_PATH }}/*rootfs.tar.gz
        openwrt_board: ${{ env.openwrt_board }}
        openwrt_kernel: ${{ env.openwrt_kernel }}
        auto_kernel: ${{ env.auto_kernel }}
        kernel_repo: ${{ env.kernel_repo }}
        kernel_usage: ${{ env.kernel_usage }}
        builder_name: ${{ env.builder_name }}

    - name: SSH远程连接（make menuconfig）
      if: env.SSH_ACTION == 'true'
      uses: danshui-git/debugger-action@main
